//
// Created by Administrator on 2018/12/22 0022.
//

#ifndef DISCRETEEARTH_GT_POINT_QUERY_CLOSEST_H
#define DISCRETEEARTH_GT_POINT_QUERY_CLOSEST_H

class GTPointQueryClosest {

};

#endif //DISCRETEEARTH_GT_POINT_QUERY_CLOSEST_H
