//
// Created by Administrator on 2018/12/22 0022.
//

#ifndef DISCRETEEARTH_GT_SHAPE_QUERY_CONTAIN_VERTEX_H
#define DISCRETEEARTH_GT_SHAPE_QUERY_CONTAIN_VERTEX_H

class GTShapeQueryContainVertex {

};

#endif //DISCRETEEARTH_GT_SHAPE_QUERY_CONTAIN_VERTEX_H
