//
// Created by Administrator on 2018/12/22 0022.
//

#ifndef DISCRETEEARTH_GT_SHAPE_QUERY_INTERSECT_H
#define DISCRETEEARTH_GT_SHAPE_QUERY_INTERSECT_H

class GTShapeQueryIntersect {

};

#endif //DISCRETEEARTH_GT_SHAPE_QUERY_INTERSECT_H
