//
// Created by Administrator on 2018/12/22 0022.
//

#ifndef DISCRETEEARTH_GT_SHAPE_QUERY_CONTAIN_POINT_H
#define DISCRETEEARTH_GT_SHAPE_QUERY_CONTAIN_POINT_H

class GTShapeQueryContainPoint {

};

#endif //DISCRETEEARTH_GT_SHAPE_QUERY_CONTAIN_POINT_H
