//
// Created by Administrator on 2018/12/22 0022.
//

#ifndef DISCRETEEARTH_GT_REGION_TERM_GENERATOR_H
#define DISCRETEEARTH_GT_REGION_TERM_GENERATOR_H

class GTRegionTermGenerator {

};

#endif //DISCRETEEARTH_GT_REGION_TERM_GENERATOR_H
